# Generated by Django 3.1.4 on 2020-12-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_defense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='website',
            new_name='website_id',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='page',
            new_name='page_id',
        ),
    ]
